### ISSUE TITLE
[Feature Request] Advanced plugin "key up" functionality

### ISSUE THREAD

**Issue by ntoff** [BarRaider/streamdeck-voicemeeter#1]
Great plugin.

In the voicemeeter macro buttons app you can assign functions when the buttons are let go of 
![image](https://user-images.githubusercontent.com/9030085/51176171-f822b380-1907-11e9-92ca-030ef8711cf9.png)
this is useful for resetting settings that get changed on button-press, stopping sounds being played, etc. Would it be possible to add key-up functionality to the advanced plugin? Thanks for the great work.

**Comment by BarRaider** [comment]
Hi,

Sorry for the late reply. I have added this request to the list of feature requests. 
You can monitor the list of feature requests on my Discord server. Link can be found at https://barraider.github.io/

**Comment by BarRaider** [comment]
This has been added as part of the new VoiceMeeter PTT action
