### ISSUE TITLE
Shutdown error on Windows 10

### ISSUE THREAD

**Issue by DudeMcGee** [BarRaider/streamdeck-voicemeeter#10]
When I shut down my Windows 10 laptop (v1809, 17763.316) streamdeck-voicemeeter presents a msg-box:

---
com.barraider.voicemeeter.sdPlugin.exe - Application Error

The application was unable to start correctly (0xc0000142).
Click OK to close the application.
---

This error appears on every shutdown.

My Streamdeck app is updated, v4.1.0.9958 with also the newest firmware on the deck.

**Comment by BarRaider** [comment]
Hey @DudeMcGee , thanks for the report!
I've been able to reproduce this and traced it down to a bug in the Stream Deck. I've notified Elgato and expect them to resolve it in the next update...

**Comment by DudeMcGee** [comment]
Great news, thanks a lot!
