### ISSUE TITLE
SD Multi-Actions don't work any more 

### ISSUE THREAD

**Issue by JoergAp** [BarRaider/streamdeck-voicemeeter#11]
After releasing Version 1.2 the combination of streamdeck-voicemeeter actions combined in a stream deck multi action does not work any more. Although actions work when carried out seperately they won't work when combined in a multi action. 

![image](https://user-images.githubusercontent.com/46818081/54058326-d3570800-41f5-11e9-9b4e-f238d75c5a7f.png)

**Comment by BarRaider** [comment]
Hey @JoergAp - Thanks for the update!
Already fixed and working on an official release at this very minute.
You can actually already download v1.3 that solves this from the Releases tab ;)

**Comment by JoergAp** [comment]
you are quick as hell ;)

**Comment by BarRaider** [comment]
Haha I try ;)
