### ISSUE TITLE
[Feature Requests] *STICKY*

### ISSUE THREAD

**Issue by BarRaider** [BarRaider/streamdeck-voicemeeter#12]
1. Simple Toggle Mode for the Advanced Toggle which just toggles between the two settings. Can be helpful in Gain for instance that is not True/False

**Comment by JoergAp** [comment]
Create an "multi state display" action depending on certain values or range of values to be combined with different icons.

example gain:
gain <= 10	-> Icon 1   
gain <=6  	-> Icon 2
gain = 0   	-> Icon 3
gain > 0   	-> Icon 4
gain >= 6	-> Icon 5

**Comment by alterscape** [comment]
Any chance for "modify value" logic? IE: "each time button is pressing, Bus[0].Gain += 1" ? Trying to set up buttons as "gain up" and "gain down" for VAIO and AUX in Banana.
