### ISSUE TITLE
"VoiceMeeter not running" error after PC boot

### ISSUE THREAD

**Issue by r00tusrDE** [BarRaider/streamdeck-voicemeeter#13]
Every time I boot up Windows I get an error icon on my streamdeck that tells me voicemeeter is not startet. The buttons are not working in this state. The problem is: the streamdeck software starts before voicemeeter. So I have to restart the streamdeck software every time to get the buttons to work again...

![screenshot](https://user-images.githubusercontent.com/30771342/54459189-30a70800-4766-11e9-96d7-ff04e7b66f4c.png)

Maybe you can fix it like this: if voicemeeter is not running -> check every x seconds if voicemeeter is running.

You can ask me anytime for clarification.

**Comment by BarRaider** [comment]
Hi,
It DOES check every few seconds if VM is online and then changes the icons back to normal once it locates VM. Olease try closing VM and reopening it once you have everything working and check if it still reproduces

**Comment by r00tusrDE** [comment]
I tested my problem again and I have to correct my issue: After VM is running I can control VM but the buttons are still showing the "not running" icon. A restart of VM changes nothing. I have to restart/start the streamdeck software **after** VM has been started.
