### ISSUE TITLE
[Feature Request] 2 Position Keypress on Advanced Plugin & Increase/Decrease Gain by X on click

### ISSUE THREAD

**Issue by Inzaniity** [BarRaider/streamdeck-voicemeeter#2]
First of all, awesome plugin!

~Would be nice to have a 2-Position-Button, kinda like the Macro Buttons of Voicemeeter offer. This is handy when you want to mute music just for yourself (Strip[X].A1 = 0/1).~

Also it would be awesome to be abte to increase or decrease the gain of a strip by a set value. So everytime I hit the button it in/decreses by 10db or something.

Kepp it up!

**Comment by hringriin** [comment]
It already works :)

Add a `VoiceMeeter Advanced Click/Long-Click` and put `Strip[0].gain+=1;` into the field `Key Press`. Voila.

The essence is: +=1 or += whatever value you want. This works with -= as well.

If you want the current value be visible on the button, add `Strip[0].gain` in the field `Title Value` and select `VoiceMeeter Value` from the ***second*** field, named `Title`.
