### ISSUE TITLE
[Feature Request] Enable Strip[i].[A1, A2, A3] settings to be toggled

### ISSUE THREAD

**Issue by ICiscoStu** [BarRaider/streamdeck-voicemeeter#21]
Hi!

it would be great to add the option to be able to update the A1 - A4 strip values using the modify setting, currently I route everything that goes to the stream through A3, and my personal audio monitor through A1.

 I'm currently in need, once I go to break on my stream, to disable A3 for on a couple of strips, so the stream still listens to music while discord and myself are muted for them.

Having the option to modify this setting via stream deck will alleviate a huge headache I'm currently having by manually going into the software instead of using the powerful multiAction feature from streamdeck

thanks in advance if you can make it

**Comment by BarRaider** [comment]
This already exists using the "VM Advanced" plugins
