### ISSUE TITLE
Add to "Voicemeter Advanced Toggle" remote command (vban)

### ISSUE THREAD

**Issue by mips81** [BarRaider/streamdeck-voicemeeter#27]
Hi,
Please, add to "Voicemeter Advanced Toggle" remote command (vban).

Trigger IN
```
BEGIN_SECTION("vban1")
Strip(0).Mute=1;
END_SECTION
```

Trigger OUT
```
BEGIN_SECTION("vban1")
Strip(0).Mute=0;
END_SECTION
```
Thank you

**Comment by BarRaider** [comment]
Hi,
VBan actually has it's own plugin in the Stream Deck store.
