### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by ZloyKott** [BarRaider/streamdeck-voicemeeter#35]
Every time i play Division 2 plugin crashes

https://i.imgur.com/BH64aWM.jpg

https://i.imgur.com/avfDA8u.png

![ApplicationFrameHost_lP4l5XRrtT](https://user-images.githubusercontent.com/58218267/69634180-c075b380-1062-11ea-9319-e372c23d93b0.png)
![TheDivision2_kNqa2h11ux](https://user-images.githubusercontent.com/58218267/69634181-c075b380-1062-11ea-82ef-58267f5c17a8.jpg)

**Comment by BarRaider** [comment]
Sorry, cannot read the text as it's not in English.
I recommend reinstalling VoiceMeeter. If that doesn't help, head over to my Discord server for support. http://discord.barraider.com
