### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Kiwiiix** [BarRaider/streamdeck-voicemeeter#4]
![image](https://user-images.githubusercontent.com/46799808/51355721-4a0a3b80-1ab8-11e9-83fe-3fc1b9832069.png)

Hi ! 
I'm a french newbie in programming and i download u'r extension for StreamDeck. 
Can you help me. I want to make a shortcut for on/off A3 on Discor. How can i do it ? 

Thanks You !

**Comment by Inzaniity** [comment]
Use VoiceMeeter Advanced Toggle in StreamDeck

Mode1 Key Press = `Strip[4].A3 = 1;`
Mode 1 Check: `Strip[4].A3`
Mode 2 Key Press = `Strip[4].A3 = 0;`

If you put `Strip[4].A3` in the Title Value it shows 1(on) or 0(off) on the button
