### ISSUE TITLE
VoiceMeeter Modify Setting does not accept user defined title

### ISSUE THREAD

**Issue by hringriin** [BarRaider/streamdeck-voicemeeter#5]
If I use a `VoiceMeeter Modify Setting`-button, all I can do is leave the title setting to `VoiceMeeter Value`. Setting it to `-UserDefined-` does not throw any error, but regardless of the field `Title`, the value is the last one set by `VoiceMeeter Value`.

... if I could make myself clear :/

Example:
```
Title:              asdf
Param:              gain
Strip/Bus:          Strip
Strip/Bus Num:      0
Value:              2
Long-Press Value:   4
Title:              VoiceMeeter Value
```
--> The title shown on the button is either `2` or `4`, depending on how long you pressed the button. Alright.

If I change the setting `Title:` from `VoiceMeeter Value` to `-UserDefined-` I can now enter any value I want in the first `Title:` field (which all in all is a bit misleading, by the way), the button still shows either `2` or `4`, depending on what you did, before you edit the *second* `Title:` field.

**Comment by BarRaider** [comment]
Hi,

Sorry for the late reply. This sounds like a bug. I have added this to the list of issues.
You can monitor the list of issues on my Discord server. Link can be found at https://barraider.github.io/

**Comment by hringriin** [comment]
> Sorry for the late reply.

Never mind :)

I cannot find any kind of list on the discord server, especially no list of issues. Is discord capable of providing direct links to those lists or do I have to claim (create) a Discord account first?

**Comment by BarRaider** [comment]
Yep.
Sorry if it feel odd to you.

**Comment by BarRaider** [comment]
Yep.
Sorry if it feels odd to you.
