### ISSUE TITLE
Advanced toggle: Mode cehck images not working

### ISSUE THREAD

**Issue by enTyoiable** [BarRaider/streamdeck-voicemeeter#51]
Hey there, 

At the latest version (1.8 & SD v4.8.1.13027) the advanced toggles I've been using are not displaying the images anymore, even though they worked fine in a previous version (SD v4.25.1.10055, I've missed a few updates - reverting to this version will resolve this issue,)). 

The action itself is okay, so it does do what it supposed to do in Voicemeeter. I've originally had some adv toggles used as mute toggles, but have replaced them with the 'real mute/unmute functions'. The below examples remains though: Switching the virtual inputs A1-A2-A3 on or off and setting the bus 1 mode to either normal or TV. I tried remaking the adv toggle, and putting the images in another directory but both did not yield any other results. It seems to me that the mode1 check is not working anymore. 

Example1:
Mode1 key press: Strip[3].a2=1
Mode2 key press: Strip[3].a2=0
Mode1 Check: Strip[3].a2

Example2:
Mode1 key press: Bus[1].mode.normal=1;
Mode2 key press: Bus[1].mode.tv=1;
Mode1 Check: Bus[1].mode.normal

Also the Title prefix, value, enabled and disabled text field do not seem to work (anymore). Doesn't matter if I set the title to voicemeeter value or user defined.

**Comment by BarRaider** [comment]
I have confirmed there is no issue with the plugin itself, head over to our Discord for support with your specific setup. http://discord.barraider.com
