### ISSUE TITLE
VoiceMeter Advanced Toggle - Unable to .FadeTo

### ISSUE THREAD

**Issue by BulldogMW** [BarRaider/streamdeck-voicemeeter#7]
In the VoiceMeter.Remote I use a hot key to fade music in and out.

I used the Advanced toggle to try and do the same and it seems to only work one way and then won't go back. It also does not toggle the images.

Example Code (Pulled this code from VoicemeterRemoteAPI.pdf): 
```
Mode 1: Strip(1).FadeTo= (-60.0, 4000);
Mode 2: Strip(1).FadeTo= (-15.0, 4000);
```
I tested the same thing for my Microphone and it is working perfectly.
```
Strip(0).B1= (1);
Strip(0).B1= (0);
```

**Comment by BarRaider** [comment]
Hi,

Sorry for the late reply.
Can you try using the Advanced Click/Long-Click and see if it works there?
If you're still having issues, I have a dedicated help channel on my Discord server.Link can be found at https://barraider.github.io/

**Comment by BulldogMW** [comment]
Thanks for the advice. That works. It still acted weird with the long press where it didn't always register the action. I ended up having to make it two separate buttons using the Advanced Click/Long-Click feature to get it work work every time accurately.
