### ISSUE TITLE
Gain value to long

### ISSUE THREAD

**Issue by ledepede** [BarRaider/streamdeck-voicemeeter#8]
When a key is showing the gain value, it can get to long, so that it is impossible to read it.

![b1cb8a5d752e8ce6d9d5d76ca145c4f1](https://user-images.githubusercontent.com/6809587/53112021-a260ad00-353e-11e9-9efa-be87a485c3f5.png)
)

**Comment by BarRaider** [comment]
Hi, 

That is definitely a bug. I will add it to the list of bugs. You can monitor the list of issues on my Discord server. Link can be found at https://barraider.github.io/
