### ISSUE TITLE
VoiceMeeter Advanced Toogle - Unable to choose images 2nd

### ISSUE THREAD

**Issue by JoergAp** [BarRaider/streamdeck-voicemeeter#9]
Hi,

after the last StreamDeck update the behavior of this error has changed. Now your are simply not able to choose specific pic files when using the "Advanced Toogle." If this must be resolved in the StreamDeck software any idea where to report this?

Pic search in "Advanced Toogle"
![image](https://user-images.githubusercontent.com/46818081/53622695-f59bc500-3bfa-11e9-93fa-fdd5809eb9fa.png)

Pic search using standard StreamDeck buttons
![image](https://user-images.githubusercontent.com/46818081/53622704-fdf40000-3bfa-11e9-9c7c-05f585f04378.png)

**Comment by BarRaider** [comment]
Hi,
I've noticed all your images are *.ico and it's not on the list of supported images.
I can add *.ico too in the next update...
For now, you can write the name of the file even though it's empty and it should load it.
If you need more help - you can contact me on my discord server. Link is at: https://barraider.github.io/
